### ISSUE TITLE
Idea to improve rootless mode

### ISSUE THREAD

**Issue by probonopd** [autc04/executor#46]
It seems like there is some sort of fully transparent window. On systems that draw shadows behind windows this results in an ugly "ghost shadow". Can that transparent window be made fullscreen?

This is the Qt version:

![image](https://user-images.githubusercontent.com/2480569/113477423-e3e41600-9481-11eb-9217-d9ee55b8bbf4.png)

Making it fullscreen would also have the advantage that hopefully the Mac menu bar would end up at the real top of the screen.

**Comment by autc04** [comment]
That's whats already being done on Macs: you can hack the `#ifdef __APPLE__` in `qt.cpp` line 193.

The problem here is that it depends on what your desktop environment is doing. On my GNOME3 desktop, it is appropriate to not cover the status bar at the top of the screen, and on an Ubuntu GNOME3 desktop, it would also be very bad to cover the dock on the left side of the screen.
Likewise, Windows users probably don't expect windows on top of their task bar.
By contrast, on the Mac, that's exactly what is done, plus some extra hacks.

The ghost shadow really shouldn't be there, the window has the `Qt::NoDropShadowWindowHint` set, which your desktop environment apparently ignores.

So, in the end, this should probably be a configuration option...

**Comment by probonopd** [comment]
This did not do the trick for me yet:

```
--- src/config/front-ends/qt/qt.cpp.orig        2021-04-03 12:27:21 UTC
+++ src/config/front-ends/qt/qt.cpp
@@ -26,10 +26,8 @@
 #include <unordered_map>
 #include <condition_variable>
 
-#ifdef __APPLE__
 void macosx_hide_menu_bar(int mouseX, int mouseY, int width, int height);
 void macosx_autorelease_pool(const std::function<void ()>& fun);
-#endif
 #include <../x/x_keycodes.h>
 
 #ifdef STATIC_WINDOWS_QT
```

**Comment by probonopd** [comment]
This change does **not** make it fullscreen for me:

```
--- src/config/front-ends/qt/qt.cpp.orig        2021-04-03 13:14:54 UTC
+++ src/config/front-ends/qt/qt.cpp
@@ -194,7 +194,7 @@ bool QtVideoDriver::setMode(int width, int height, int
         macosx_hide_menu_bar(500, 0, 1000, 1000);
         QVector<QRect> screenGeometries = getScreenGeometries();
 #else
-        QVector<QRect> screenGeometries = getAvailableScreenGeometries();
+        QVector<QRect> screenGeometries = getScreenGeometries();
 #endif
 
         printf("set_mode: %d %d %d\n", width, height, bpp);
```

**Comment by probonopd** [comment]
Editing `src/config/front-ends/qt/qt.cpp` and changing line 215 from `window->showMaximized();` to `window->showFullScreen();` did the trick for me.

**Comment by probonopd** [comment]
![image](https://user-images.githubusercontent.com/2480569/113487968-64733880-94bb-11eb-9747-53cfd7b37a6e.png)
